import "~/styles/globals.css";
import '@livekit/components-styles';




import { TRPCReactProvider } from "~/trpc/react";




export const metadata = {
  title: "GestureTalk",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/snapedit_1712040610628.png" }],
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head></head>
      <body>
        <TRPCReactProvider>{children}</TRPCReactProvider>
      </body>
    </html>
  );
}
